# Generated by Django 3.1.2 on 2020-10-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='take_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stucourse', to='smapi.section'),
        ),
    ]
