# Generated by Django 3.1.2 on 2020-10-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('N', 'None')], default='None', max_length=10),
        ),
    ]
