# Generated by Django 3.1.2 on 2020-10-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0002_auto_20201021_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
