# Generated by Django 3.1.2 on 2020-10-18 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0002_takes_course_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='smapi.teaches')),
            ],
        ),
        migrations.CreateModel(
            name='GiveExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stuexam', to='smapi.takes')),
                ('stuexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuexam', to='smapi.exam')),
            ],
        ),
        migrations.CreateModel(
            name='GiveMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('examobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examobj', to='smapi.giveexam')),
            ],
        ),
    ]
