# Generated by Django 3.1.2 on 2020-10-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('salary', models.IntegerField()),
                ('dept_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smapi.department')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='smapi.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(check=models.Q(budget__gte=0), name='budget_gte_18'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.CheckConstraint(check=models.Q(salary__gte=29000), name='salary_gte_29000'),
        ),
    ]
