# Generated by Django 3.1.2 on 2020-10-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0002_auto_20201014_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='steacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='smapi.teaches'),
            preserve_default=False,
        ),
    ]
