# Generated by Django 3.1.2 on 2020-10-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0003_auto_20201007_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dept_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='smapi.department'),
        ),
    ]
