# Generated by Django 3.1.2 on 2020-10-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0003_exam_giveexam_givemarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveexam',
            name='stuexam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stuexam', to='smapi.exam'),
        ),
        migrations.AlterField(
            model_name='givemarks',
            name='examobj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examobj', to='smapi.giveexam'),
        ),
    ]
