# Generated by Django 3.1.2 on 2020-10-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0003_takes_steacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='take_course',
        ),
    ]
