# Generated by Django 3.1.2 on 2020-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0004_auto_20201007_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
