# Generated by Django 3.1.2 on 2020-10-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0004_auto_20201018_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveexam',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='takesstudent', to='smapi.takes'),
        ),
    ]
