# Generated by Django 3.1.2 on 2020-10-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0005_auto_20201018_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('tid', 'teachcourse')},
        ),
    ]
