# Generated by Django 3.1.2 on 2020-10-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0005_remove_takes_gpa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('sid', 'steacher')},
        ),
    ]
