# Generated by Django 3.1.2 on 2020-10-07 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0005_auto_20201007_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
