# Generated by Django 3.1.2 on 2020-10-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0006_auto_20201014_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takes',
            old_name='steacher',
            new_name='take_course',
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('sid', 'take_course')},
        ),
    ]
