# Generated by Django 3.1.2 on 2020-10-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0006_auto_20201019_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='teacher',
            new_name='teaches',
        ),
        migrations.RenameField(
            model_name='giveexam',
            old_name='stuexam',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='giveexam',
            old_name='student',
            new_name='takes',
        ),
        migrations.RenameField(
            model_name='givemarks',
            old_name='examobj',
            new_name='giveexam',
        ),
    ]
