# Generated by Django 3.1.2 on 2020-10-07 23:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0006_auto_20201007_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='instructor',
            name='salary_gte_29000',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='salary',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(29000), django.core.validators.MaxValueValidator(300000)]),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='smapi.department'),
        ),
    ]
