# Generated by Django 3.1.2 on 2020-10-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0007_auto_20201014_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='take_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalstudents', to='smapi.teaches'),
        ),
    ]
