# Generated by Django 3.1.2 on 2020-10-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0007_auto_20201019_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='teaches',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='giveexam',
            old_name='takes',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='giveexam',
            old_name='exam',
            new_name='stuexam',
        ),
        migrations.RenameField(
            model_name='givemarks',
            old_name='giveexam',
            new_name='examobj',
        ),
    ]
