# Generated by Django 3.1.2 on 2020-10-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0008_auto_20201007_2341'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='budget_gte_18',
        ),
        migrations.AlterField(
            model_name='department',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
    ]
