# Generated by Django 3.1.2 on 2020-10-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0008_auto_20201014_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deptstudents', to='smapi.department'),
        ),
    ]
