# Generated by Django 3.1.2 on 2020-10-08 00:08

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0009_auto_20201007_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('salary', models.IntegerField()),
                ('dept_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smapi.department')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor',
                                             to='smapi.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=255),
        ),
    ]
