# Generated by Django 3.1.2 on 2020-10-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0009_auto_20201020_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takesstudent', to='smapi.takes'),
        ),
        migrations.AlterUniqueTogether(
            name='giveexam',
            unique_together={('stuexam', 'student')},
        ),
    ]
