# Generated by Django 3.1.2 on 2020-10-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0011_auto_20201008_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Fa', 'Fall'), ('Su', 'Summer'), ('Wi', 'Winter'), ('Sp', 'Spring')], default='Fall', max_length=10)),
                ('year', models.DateField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachcourse', to='smapi.course')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='smapi.instructor')),
            ],
        ),
    ]
