# Generated by Django 3.1.2 on 2020-10-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0012_auto_20201008_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_name',
        ),
    ]
