# Generated by Django 3.1.2 on 2020-10-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0015_auto_20201013_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='smapi.teaches'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takes',
            name='course_marks',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
