# Generated by Django 3.1.2 on 2020-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0016_auto_20201013_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='teacher',
        ),
        migrations.AddField(
            model_name='takes',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='smapi.Teaches'),
        ),
    ]
