# Generated by Django 3.1.2 on 2020-10-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapi', '0017_auto_20201013_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='teacher',
        ),
        migrations.AddField(
            model_name='takes',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='smapi.teaches'),
            preserve_default=False,
        ),
    ]
